- name: Include Github Deploy SSL certificates
  include_vars:
    file: certificate.yml
    name: certificate
  ignore_errors: True

- name: make sure Github Deploy SSL certificate is installed
  copy:
    content: "{{ certificate.ssl_certificate }}"
    dest: "/etc/ssl/certs/github_deploy_cert.pem"
    owner: root
    group: root
    mode: 0644
  when: certificate is defined
  ignore_errors: True

- name: make sure Github Deploy SSL private key is installed
  copy:
    content: "{{ certificate.ssl_private_key }}"
    dest: "/etc/ssl/private/github_deploy_key.pem"
    owner: root
    group: root
    mode: 0600
  no_log: true
  when: certificate is defined
  ignore_errors: True

- name: make sure git is installed
  apt:
    name: git
    state: present
    update_cache: yes

- name: Pull {{project_main_controller}} ({{branch}} - {{repo}}) from github with certificate
  git:
    repo: "{{repo}}"
    dest: "{{path}}"
    version: "{{branch}}"
    key_file: "/etc/ssl/private/github_deploy_key.pem"
    accept_hostkey: yes
    update: yes
    force: yes
  tags: git
  when: certificate is defined

- name: Pull {{project_main_controller}} ({{branch}} - {{repo}}) from github
  git:
    repo: "{{repo}}"
    dest: "{{path}}"
    version: "{{branch}}"
    update: yes
    force: yes
    track_submodules: yes
  tags: git
  when: certificate is not defined