- name: make sure git is installed
  apt:
    name: git
    state: present
    update_cache: yes

- name: Pull public repository
  include_tasks: pull.yml
  when: git_pull_github_token is undefined

- name: Pull protected repository
  include_tasks: pull_with_token.yml
  when: git_pull_github_token is defined