
- name: Create Github.com deploy key using personal token
  include_role:
    name: configure.github-deploy-key
  vars:
    github_deploy_api_owner: "{{kowner | mandatory}}"
    github_deploy_api_repo: "{{repo | mandatory}}"
    github_deploy_api_token: "{{github_token | mandatory}}"
#        github_deploy_ssh_keygen_type: "{{ lookup('env','SSH_KEY_TYPE') }}"

- name: Create a temporary directory for the key
  command: 'mktemp -d'
  register: deploy_code_key_dir_create

- name: Set a fact for the directory path
  set_fact:
    deploy_code_key_dir: "{{ deploy_code_key_dir_create.stdout }}"

- name: Create a temporary private key file
  lineinfile:
    create: yes
    state: present
    line: "{{ github_deploy_ssh_private_key }}"
    dest: "{{ deploy_code_key_dir }}/key"
    mode: 0600

- name: Pull ({{branch}} - {{ssh_route}}) from github with certificate
  git:
    repo: "{{ssh_route | mandatory}}"
    dest: "{{path | mandatory}}"
    version: "{{branch | mandatory}}"
    key_file: "{{ deploy_code_key_dir }}/key"
    update: yes
    force: yes
  changed_when: true
  notify:
    - Delete the transient deploy key host temp dir
    - Revoke Github deploy key
  tags: git