- name: Pull ({{git_pull_branch}} - {{git_pull_https_route}}) from github
  git:
    repo: "{{git_pull_https_route | mandatory}}"
    dest: "{{git_pull_path | mandatory}}"
    version: "{{git_pull_branch | mandatory}}"
    update: yes
    force: yes
    recursive: no
  tags: git
  changed_when: true