---
develop:
  children:
    api:
      hosts: api.openecoe
    webui:
      hosts: webui.openecoe
    chrono:
      hosts: chrono.openecoe
  vars:
    #Ansible Parameters
    ansible_connection: local

    #Ansible connection by SSH to remote machine
    #ansible_connection: ssh
    #ansible_user: openecoe
    #ansible_port: 22
    #ansible_host: "{{domain}}"
    #ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"