#supervisor_unix_http_server_socket_path: /var/run/supervisord.sock

supervisor_programs:
  - name: '{{project_main_controller}}'
    command: "{{venv_path}}/bin/gunicorn{% if gunicorn_params is defined %} {{gunicorn_params}}{% endif %} -b {{gunicorn_server}} -w {{app_workers}} {{gunicorn_module}} --access-logfile -"
    state: present
    configuration: |
      directory={{project_path}}
      autostart=true
      autorestart=true
      stopasgroup=true
      killasgroup=true
      stderr_logfile=/var/log/{{project_main_controller}}-err.log
      stdout_logfile=/var/log/{{project_main_controller}}-out.log
      stopsignal=INT
      environment = FLASK_APP="{{project_main_controller}}"