---
routes:
  protocol: "http"
  webui:
    host: "{{domain}}"
    port: 80
    port_ssl: 443
  api:
    host: "api.{{domain}}"
    port: 80
    port_ssl: 443
  chrono:
    host: "chrono.{{domain}}"
    port: 6080
    port_ssl: 6443

chrono_route: "{{routes.protocol}}://{{routes.chrono.host}}:{{routes.chrono.port}}"

# App environment
base_path: /opt

#Supervisor parameters
supervisor_inet_http_server_enable: true
supervisor_inet_http_server_port: '*:9001'