---
routes:
  protocol: "http"
  webui:
    host: "{{domain}}"
    port: 80
    port_ssl: 443
  api:
    host: "api.{{domain}}"
    port: 80
    port_ssl: 443
  chrono:
    host: "chrono.{{domain}}"
    port: 6080
    port_ssl: 6443

chrono_route: "{{routes.protocol}}://{{routes.chrono.host}}:{{routes.chrono.port}}"

# App environment
base_path: "/opt/{{domain}}"
database: "openECOE"

#Supervisor parameters
supervisor_user: root
supervisor_password: '1234567890'

supervisor_inet_http_server_enable: true
supervisor_inet_http_server_port: '*:9001'

git_owner: "openECOE"
