---
base_path: /opt

app_secret_key: '12345678901234567890123456789012'
app_workers: 1

supervisor_inet_http_server_enable: true
supervisor_inet_http_server_port: '*:9001'

supervisor_started: false
nginx_remove_default_vhost: true

organization: "Universidad Miguel Hernandez"
domain: openecoe.umh.es

admin_users:
  admin:
    email: "admin@{{domain}}"
    name: Admin
    surname: OpenECOE
    password: 1234567890

database_user: "openecoe"
database_password: "1234567890"

supervisor_user: root
supervisor_password: '1234'



ansible_connection: local

#Ansible connection by SSH to remote machine
#ansible_connection: ssh
#ansible_user: openecoe
#ansible_port: 22
#ansible_host: "{{domain}}"
#ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"