---
ansible_connection: local

base_path: /opt

app_workers: 1

supervisor_user: root
supervisor_password: '1234'

supervisor_inet_http_server_enable: true
supervisor_inet_http_server_port: '*:9001'

supervisor_started: false