---
# Chrono Environment Config
project_main_controller: openECOE-CHRONO
project_path: "{{base_path}}/{{project_main_controller}}"

venv_path: "{{base_path}}/.venv_chrono"
requirements_path: "{{project_path}}/requirements.txt"

# Gunicorn config
gunicorn_server: "localhost:9000"
gunicorn_params: "--worker-class eventlet"
gunicorn_module: "{{project_main_controller}}:app"