---
hostname: webui-openecoe
app_fqdn: "{{domain}}"
app_port: 80

#ansible_connection: ssh
#ansible_user: vagrant
#ansible_port: 2252
#ansible_host: openecoe
#ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/openecoe_private_key"

# Enviroment Config
project_main_controller: openECOE-WebUI
project_path: "{{base_path}}/{{project_main_controller}}"

venv_path: "{{project_path}}/.venv"
requirements_path: "{{project_path}}/requirements.txt"

git_repo: "https://github.com/openECOE/openECOE-WebUI-ng.git"
git_branch: master

# Enviroment Config
app_debug: False
app_testing: False

api_uri: "http://api.{{domain}}"
api_route: "{{api_uri}}/api"
api_auth_token: "{{api_uri}}/auth/tokens"

chrono_route: "http://{{domain}}:6080"