# Manage the state of program to be in 'started' state.
- name: Ensure old WebUI supervisor is removed
  supervisorctl:
    name: "openECOE-WebUI"
    state: absent
    username: "{{ supervisor_user }}"
    password: "{{ supervisor_password }}"

- name: Install Packages
  apt:
    name: ['build-essential',
           'mcrypt',
           'curl']
    update_cache: yes
    state: latest

- name: Install NodeJS
  include_role:
    name: geerlingguy.nodejs

- name: Get project {{project_main_controller}} from Github ({{git_repo}})
  include_role:
    name: production.git-pull
  vars:
    git_pull_owner: "{{git_owner}}"
    git_pull_repo: "{{git_repo}}"
    git_pull_branch: "{{git_branch}}"
    git_pull_path: "{{project_path}}"
  when: env != 'local'
  register: git_finished

- name: Create environment configuration file
  template:
    src: environment.prod.ts
    dest: "{{project_path}}/src/environments/environment.prod.ts"
    mode: 0644
    force: yes

- name: Running NPM install
  npm:
    path: "{{project_path}}"
    state: latest
  register: npm_finished
#  when: git_finished.changed

- name: Build Angular Configuration
  shell: "./node_modules/@angular/cli/bin/ng build --configuration={{ng_config}}"
  args:
    chdir: "{{project_path}}"
  register: ngbuild_finished
  when: ng_config is defined
  tags: "angular_build"

- name: Build Angular Prod
  shell: "./node_modules/@angular/cli/bin/ng build --prod --aot"
  args:
    chdir: "{{project_path}}"
  register: ngbuild_finished
  when: ng_config is undefined
  tags: "angular_build"

- name: Create nginx hosts
  when: env != 'local'
  include_role:
    name: production.nginx
  vars:
    nginx_vhosts: "{{vhosts}}"
  tags: nginx_webui