- name: Install Packages
  apt:
    name: ['build-essential',
           'mcrypt',
           'curl']
    update_cache: yes
    state: latest

- name: Install NodeJS
  include_role:
    name: geerlingguy.nodejs

- name: Get project {{ng_main_controller}} from Github ({{ng_git_repo}})
  include_role:
    name: production.git-pull
  vars:
    repo: "{{ng_git_repo}}"
    branch: "{{git_branch}}"
    path: "{{ng_project_path}}"
  when: env == 'production'
  register: git_finished

- name: Running NPM install
  npm:
    path: "{{ng_project_path}}"
    state: latest
  register: npm_finished
#  when: git_finished.changed

- name: Build Angular Configuration
  shell: "./node_modules/@angular/cli/bin/ng build --configuration={{ng_config}} --aot --base-href {{ng_base_href}}/"
  args:
    chdir: "{{ng_project_path}}"
  register: ngbuild_finished
  when: env != 'production'

- name: Build Angular Prod ({{ng_base_href}})
  shell: "./node_modules/@angular/cli/bin/ng build --prod --aot --base-href {{ng_base_href}}/"
  args:
    chdir: "{{ng_project_path}}"
  register: ngbuild_finished
  when: env == 'production'