---
- name: Create a temporary directory for the key
  tempfile:
    state: directory
    prefix: "{{ github_deploy_key_temp_dir | default(omit) }}"
  register: github_deploy_key_temp_dir_create

- name: Create a temporary private key file
  lineinfile:
    create: yes
    state: present
    line:   "{{ github_deploy_ssh_private_key }}"
    dest:   "{{ github_deploy_key_temp_dir_create.path }}/{{ github_deploy_key_name }}"
    mode:   "{{ github_deploy_key_mode }}"
    owner:  "{{ github_deploy_key_owner | default(omit) }}"
    group:  "{{ github_deploy_key_group | default(omit) }}"

- name: Set a fact for the key path for use later
  set_fact:
    github_deploy_ssh_private_key_path: "{{ github_deploy_key_temp_dir_create.path }}/{{ github_deploy_key_name }}"
...
