---
- name:         Gather the github remote host public key
  command:      "{{ github_deploy_ssh_keyscan_executable }} -H github.com"
  register:     github_deploy_keyscan_output
  delegate_to:  "{{ github_deploy_local_delegate }}"
  run_once:     yes

- name: Set a fact for later use in populating an ssh_known_hosts file
  set_fact:
    github_deploy_keyscan: "{{ github_deploy_keyscan_output.stdout }}"

- name: Add the Github keyscan to the host file
  lineinfile:
    line:   "{{ github_deploy_keyscan }}"
    create: yes
    state:  present
    dest:   "{{ github_deploy_known_hosts }}"
    owner:  "{{ github_deploy_known_hosts_owner | default(omit) }}"
    group:  "{{ github_deploy_known_hosts_group | default(omit) }}"
  become:   yes
  when:     github_deploy_keyscan_populate_host
...
