# Require file ansible_vault.pass with passsword string for Ansible Vault
---
- name: Install base dependencies
  hosts: webui
  become: yes # This means that all tasks will be executed with sudo
  roles:
    - base
    - configure

- name: Get project from Github
  hosts: chrono
  become: yes
  roles:
    - { role: production.git-pull, when: env == 'production'}

- name: Install Chrono
  hosts: chrono
  become: yes # This means that all tasks will be executed with sudo
  roles:
    - openecoe.chrono

- name: Production tasks
  hosts: chrono
  become: yes
  roles:
    - { role: production.nginx, when: env == 'production'}
    - { role: production.supervisor, when: env == 'production'}