---
# Organization settings
organization: "Universidad Miguel Hernandez"
domain: dev.openecoe.umh.es

admin_users:
  admin:
    email: "admin@{{domain}}"
    name: Admin
    surname: OpenECOE
    password: 1234567890

# App environment
env: local

git_branch: develop

# Test Enviroment Config
app_debug: True
app_testing: False

# Database settings
database_user: "openecoe"
database_password: "1234567890"

#Deactivate supervisor http server in production
supervisor_inet_http_server_enable: true