nginx_port: "{{ app_port | default('80') }}"
nginx_port_ssl: "{{ app_port_ssl | default('443') }}"

nginx_vhosts:
  - listen: "{{nginx_port}}"
    server_name: "{{app_fqdn}}"
    state: "present"
    filename: "{{project_main_controller}}_{{nginx_port}}.conf"
    template: "{{ nginx_vhost_template }}"
    extra_parameters: |
      location / {
          # forward application requests to the gunicorn server
          proxy_pass http://{{gunicorn_server}};
          proxy_redirect off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      location /static {
          # handle static files directly, without forwarding to the application
          alias {{project_path}}/static;
          expires 30d;
      }

  - listen: "{{nginx_port_ssl}} ssl" # listen on port 443 (https)
    server_name: "{{app_fqdn}}"
    state: "present"
    filename: "{{project_main_controller}}_{{nginx_port_ssl}}.conf"
    template: "{{ nginx_vhost_template }}"

    # write access and error logs to /var/log
    access_log: "/var/log/nginx/{{project_main_controller}}_access.log"
    error_log: "/var/log/nginx/{{project_main_controller}}_error.log"
    extra_parameters: |
      # location of the self-signed SSL certificate
      ssl_certificate /etc/ssl/{{app_fqdn}}.pem;
      ssl_certificate_key /etc/ssl/private/{{app_fqdn}}.pem;

      location / {
          # forward application requests to the gunicorn server
          proxy_pass http://{{gunicorn_server}};
          proxy_redirect off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      location /static {
          # handle static files directly, without forwarding to the application
          alias {{project_path}}/static;
          expires 30d;
      }