environment_config:
  FLASK_APP: "{{project_path}}/{{project_main_controller}}.py"

mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb

mysql_root_password: RmhL2MQHfq0Z36f5IUar
mysql_databases:
  - name: "{{database_name}}"
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: "{{database_user}}"
    host: "%"
    password: "{{database_password}}"
    priv: "{{database_name}}.*:ALL"

nginx_vhosts:
  - listen: "{{nginx_port}}"
    server_name: "{{app_fqdn}}"
    state: "present"
    filename: "{{project_main_controller}}_{{nginx_port}}.conf"
    template: "{{ nginx_vhost_template }}"
    extra_parameters: |
      location / {
          # forward application requests to the gunicorn server
          proxy_pass http://{{gunicorn_server}};
          proxy_redirect off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      location /static {
          # handle static files directly, without forwarding to the application
          alias {{project_path}}/app/static;
          expires 30d;
      }
      location /socket.io {
          include proxy_params;
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass http://{{gunicorn_server}}/socket.io;
      }

  - listen: "{{nginx_port_ssl}} ssl" # listen on port 443 (https)
    server_name: "{{app_fqdn}}"
    state: "present"
    filename: "{{project_main_controller}}_{{nginx_port_ssl}}.conf"
    template: "{{ nginx_vhost_template }}"

    # write access and error logs to /var/log
    access_log: "/var/log/nginx/{{project_main_controller}}_access.log"
    error_log: "/var/log/nginx/{{project_main_controller}}_error.log"
    extra_parameters: |
      # location of the self-signed SSL certificate
      ssl_certificate /etc/ssl/{{app_fqdn}}.pem;
      ssl_certificate_key /etc/ssl/private/{{app_fqdn}}.pem;

      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

      location / {
          # forward application requests to the gunicorn server
          proxy_pass http://{{gunicorn_server}};
          proxy_redirect off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      location /static {
          # handle static files directly, without forwarding to the application
          alias {{project_path}}/app/static;
          expires 30d;
      }
      location /socket.io {
          include proxy_params;
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass http://{{gunicorn_server}}/socket.io;
      }