ng_git_repo: "git@github.com:openECOE/openECOE-WebUI-ng.git"
ng_main_controller: "openECOE-WebUI-ng"

ng_project_path: "{{base_path}}/{{ng_main_controller}}"
ng_dist_path: "{{ng_project_path}}/dist/{{ng_main_controller}}"
log_file: "/var/log/nginx/{{ng_main_controller}}"

ng_vhosts:
  - listen: "{{nginx_port}}"
    server_name: "{{app_fqdn}}"
    state: "present"
    filename: "{{ng_main_controller}}_{{nginx_port}}.conf"
    template: "{{ nginx_vhost_template }}"
    # write access and error logs to /var/log
    access_log: "{{log_file}}_access.log"
    error_log: "{{log_file}}_error.log"
    extra_parameters: |
      location {{ng_base_href}}
      try_files $uri $uri/ /index.html;

  - listen: "{{nginx_port_ssl}} ssl" # listen on port 443 (https)
    server_name: "{{ng_app_fqdn}}"
    root: "{{ng_dist_path}}"
    state: "present"
    filename: "{{ng_main_controller}}_{{nginx_port_ssl}}.conf"
    template: "{{ nginx_vhost_template }}"

    # write access and error logs to /var/log
    access_log: "{{log_file}}_access.log"
    error_log: "{{log_file}}_error.log"
    extra_parameters: |
      try_files $uri $uri/ /index.html;