ng_git_repo: "git@github.com:openECOE/openECOE-WebUI-ng.git"

ng_main_controller: "openECOE-WebUI-ng"
ng_project_path: "{{base_path}}/{{ng_main_controller}}"
ng_dist_path: "{{ng_project_path}}/dist/{{ng_main_controller}}"

vhosts:
  - listen: "{{nginx_port}}"
    server_name: "{{app_fqdn}}"
    state: "present"
    filename: "{{project_main_controller}}_{{nginx_port}}.conf"
    template: "{{ nginx_vhost_template }}"
    extra_parameters: |
      root {{ng_dist_path}};

      location / {
         try_files $uri $uri/ /index.html;
       }

  - listen: "{{nginx_port_ssl}} ssl" # listen on port 443 (https)
    server_name: "{{app_fqdn}}"
    state: "present"
    filename: "{{project_main_controller}}_{{nginx_port_ssl}}.conf"
    template: "{{ nginx_vhost_template }}"

    # write access and error logs to /var/log
    access_log: "/var/log/nginx/{{project_main_controller}}_access.log"
    error_log: "/var/log/nginx/{{project_main_controller}}_error.log"
    extra_parameters: |
      # location of the self-signed SSL certificate
      ssl_certificate /etc/ssl/{{app_fqdn}}.pem;
      ssl_certificate_key /etc/ssl/private/{{app_fqdn}}.pem;

      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

      root {{ng_dist_path}};

      location / {
          try_files $uri $uri/ /index.html;
      }