- name: Get project {{project_main_controller}} from Github ({{git_repo}})
  become: yes
  include_role:
    name: production.git-pull
  vars:
    repo: "{{git_repo}}"
    branch: "{{git_branch}}"
    path: "{{project_path}}"
  when: env == 'production'

- name: Create .env configuration file
  template:
    src: env_template
    dest: "{{project_path}}/.env"
    mode: 0644

- name: Create virtualenv
  pip:
    virtualenv: "{{ venv_path }}"
    virtualenv_python: python3
    requirements: "{{ requirements_path }}"
  tags: virtualenv

- name: Create nginx hosts
  when: env == 'production'
  become: yes
  include_role:
    name: production.nginx
  ignore_errors: yes

- name: Create supervisor process
  when: env == 'production'
  become: yes
  include_role:
    name: production.supervisor