- name: Ensure Gunicorn is installed.
  pip:
    name: gunicorn
    state: present
    virtualenv: "{{ venv_path }}"
    virtualenv_python: python3
  tags: [supervisor]

- name: Stop service supervisord, if running
  become: yes
  service:
    name: supervisord
    state: stopped
  ignore_errors: yes
  tags: [supervisor]

- include_role:
    name: geerlingguy.supervisor
  tags: [supervisor]
  ignore_errors: yes

- name: Start service supervisord, if not running
  become: yes
  service:
    name: supervisord
    state: started
  ignore_errors: yes
  tags: [supervisor]