# Require file ansible_vault.pass with passsword string for Ansible Vault
---
- name: Install base dependencies
  hosts: api
  become: yes # This means that all tasks will be executed with sudo
  roles:
    - base
    - configure

- name: Install API
  hosts: api
  become: yes # This means that all tasks will be executed with sudo
  roles:
    - openecoe.api