# Require file ansible_vault.pass with passsword string for Ansible Vault
---
- name: Install base dependencies
  hosts: chrono
  become: yes # This means that all tasks will be executed with sudo
  roles:
    - base
    - configure

