---
- name: Install base dependencies
  become: yes # This means that all tasks will be executed with sudo
  hosts: all
  roles:
    - base

- name: Install API
  hosts: api
  become: yes
  roles:
    - configure
    - openecoe.api

- name: Install WebUI
  hosts: webui
  become: yes
  roles:
    - configure
    - openecoe.webui.ng

- name: Install Chrono
  hosts: chrono
  become: yes
  roles:
    - configure
    - openecoe.chrono