---
###### Flow control variables
# These change what the role will actually do

# Whether or not to enable remote key scanning of Github
github_deploy_keyscan_enable: yes

# Whether or not to populate the host with the results of the key scan
github_deploy_keyscan_populate_host: no

# Whether or not to create the private key in a temporary directory
github_deploy_create_host_key: no



# Used for delegate_to operations
github_deploy_local_delegate: '127.0.0.1'



github_deploy_key_name: 'id_deploy'
github_deploy_key_mode: '0600'
github_deploy_known_hosts: '/etc/ssh/ssh_known_hosts'

# Assumes it is in your path, but you can change it
github_deploy_ssh_keygen_executable: 'ssh-keygen'
github_deploy_ssh_keyscan_executable: 'ssh-keyscan'

# Use up to date keys over RSA where possible
github_deploy_ssh_keygen_type: 'ed25519'

github_deploy_ssh_filename: "github_{{ github_deploy_ssh_keygen_type }}"

github_deploy_ssh_dir: '~/.ssh'

github_deploy_ssh_gen_path: "{{ github_deploy_ssh_temp_dir }}/{{ github_deploy_ssh_filename }}"

github_deploy_ssh_keygen_comment: "Github deploy key generated on {{ ansible_date_time.iso8601 }}"

github_deploy_ssh_keygen_options:
  - key: '-N'
    value: "''"
  - key: '-t'
    value: "{{ github_deploy_ssh_keygen_type }}"
  - key: '-f'
    value: "{{ github_deploy_ssh_gen_path }}"
  - key: '-C'
    value: "'{{ github_deploy_ssh_keygen_comment }}'"

github_deploy_ssh_keygen_option: "{% for option in github_deploy_ssh_keygen_options %} {{ option.key }} {{ option.value | default('') }}{% endfor %}"

github_deploy_ssh_keygen_command: "{{ github_deploy_ssh_keygen_executable }} {{ github_deploy_ssh_keygen_option }}"

github_deploy_api_base: 'https://api.github.com'
github_api_deploy_key_endpoint: "/repos/{{ github_deploy_api_owner | mandatory }}/{{ github_deploy_api_repo | mandatory }}/keys"
github_api_deploy_key_add_url: "{{ github_deploy_api_base }}{{ github_api_deploy_key_endpoint }}"
github_api_deploy_key_delete_url: "{{ github_deploy_api_base }}{{ github_api_deploy_key_endpoint }}"
github_deploy_read_only: yes

github_deploy_public_key_title: "{{ github_deploy_ssh_keygen_comment }}"
...
