- name: Get project {{project_main_controller}} from Github ({{git_repo}})
  when: env == 'production'
  include_role:
    name: production.git-pull
  vars:
    repo: "{{git_repo}}"
    branch: "{{git_branch}}"
    path: "{{project_path}}"

- name: Create .env configuration file
  template:
    src: env_template
    dest: "{{project_path}}/.env"
    mode: 0644

- name: make sure git is installed
  apt:
    name: git
    state: present
    update_cache: yes

- name: Create virtualenv
  pip:
    virtualenv: "{{ venv_path }}"
    virtualenv_python: python3
    requirements: "{{ requirements_path }}"
  tags: virtualenv

- name: Upgrade API DB
  shell: "{{ venv_path }}/bin/flask db upgrade"
  args:
    chdir: "{{project_path}}"
  environment:
    FLASK_APP: "{{project_main_controller}}.py"
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  tags: upgradeAPIDB

- name: Create default Organization
  shell: "{{ venv_path }}/bin/flask create_orga --name '{{organization}}'"
  args:
    chdir: "{{project_path}}"
  environment:
    FLASK_APP: "{{project_main_controller}}.py"
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  ignore_errors: yes
  tags: createorga

- name: Create default admin users
  shell: "{{ venv_path }}/bin/flask create_user --email {{item.value.email}} --password {{item.value.password}} --name  {{item.value.name}} --surname {{item.value.surname}} --admin"
  args:
    chdir: "{{project_path}}"
  environment:
    FLASK_APP: "{{project_main_controller}}.py"
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  ignore_errors: yes
  tags: createusers
  with_dict: "{{admin_users}}"

- name: Create nginx hosts
  when: env == 'production'
  include_role:
    name: production.nginx
  ignore_errors: yes

- name: Create supervisor process
  when: env == 'production'
  include_role:
    name: production.supervisor