---
- name: Delete database with name '{{database_name}}'
  mysql_db:
    name: "{{database_name}}"
    state: absent

- name: Copy database dump file
  copy:
    src: "{{sql_dump}}"
    dest: /tmp
  register: dump_file

- debug:
    var: dump_file

- name: Restore database
  mysql_db:
    name: "{{database_name}}"
    state: import
    target: "{{dump_file.dest}}"
  when: dump_file
...